name: Social Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: guowei-gong/guowei-gong@main
        with:
          blog_rss_link: https://gongguowei.com/atom.xml
          douban_name: gongguowei01
